# Generated by Django 5.2.1 on 2025-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
