# Generated by Django 5.2.1 on 2025-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about_me', '0002_auto_20250606_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool'), ('platform', 'Platform'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
