# Generated by Django 4.2.14 on 2025-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about_me', '0003_technology_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, storage='app_about_me.storage.PdfCloudinaryStorage', upload_to='aboutme/cv/'),
        ),
    ]
