# Generated by Django 4.2.14 on 2025-06-15 19:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_about_me', '0003_technology_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cv_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='CV PDF'),
        ),
    ]
