# Generated by Django 4.2.14 on 2025-06-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about_me', '0004_alter_aboutme_cv_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='aboutme/cv/'),
        ),
    ]
