# Generated by Django 4.2.14 on 2025-06-16 14:15

import app_about_me.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about_me', '0005_alter_aboutme_cv_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, storage=app_about_me.storage.get_pdf_cloudinary_storage, upload_to='aboutme/cv/'),
        ),
    ]
